import { 
  Target, Users, TrendingUp, Building, Rocket, Settings, RefreshCw,
  DollarSign, PieChart, Search, Lightbulb, Zap, Monitor,
  Code, Smartphone, Plug, Cpu, Cloud, Database, BarChart, Bot, Lock, Server,
  Eye, Building2, Brain, Banknote, Calculator, FileText, Gem, Send,
  Handshake, Layers, Globe, Merge, Award, Shield, Network, Activity, HardDrive,
  ShieldCheck, Wifi, Workflow, Briefcase, Laptop, UserCog, ChartLine
} from "lucide-react";

export const getIcon = (iconName: string) => {
  const iconMap: Record<string, React.ReactNode> = {
    target: <Target size={24} />,
    users: <Users size={24} />,
    'trending-up': <TrendingUp size={24} />,
    building: <Building size={24} />,
    rocket: <Rocket size={24} />,
    settings: <Settings size={24} />,
    'refresh-cw': <RefreshCw size={24} />,
    'dollar-sign': <DollarSign size={24} />,
    'pie-chart': <PieChart size={24} />,
    search: <Search size={24} />,
    lightbulb: <Lightbulb size={24} />,
    zap: <Zap size={24} />,
    monitor: <Monitor size={24} />,
    code: <Code size={24} />,
    smartphone: <Smartphone size={24} />,
    plug: <Plug size={24} />,
    cpu: <Cpu size={24} />,
    cloud: <Cloud size={24} />,
    database: <Database size={24} />,
    'bar-chart': <BarChart size={24} />,
    bot: <Bot size={24} />,
    lock: <Lock size={24} />,
    server: <Server size={24} />,
    eye: <Eye size={24} />,
    'building-2': <Building2 size={24} />,
    brain: <Brain size={24} />,
    banknote: <Banknote size={24} />,
    calculator: <Calculator size={24} />,
    'file-text': <FileText size={24} />,
    gem: <Gem size={24} />,
    send: <Send size={24} />,
    handshake: <Handshake size={24} />,
    layers: <Layers size={24} />,
    globe: <Globe size={24} />,
    merge: <Merge size={24} />,
    award: <Award size={24} />,
    shield: <Shield size={24} />,
    network: <Network size={24} />,
    activity: <Activity size={24} />,
    'hard-drive': <HardDrive size={24} />,
    'shield-check': <ShieldCheck size={24} />,
    wifi: <Wifi size={24} />,
    workflow: <Workflow size={24} />,
    briefcase: <Briefcase size={24} />,
    laptop: <Laptop size={24} />,
    'user-cog': <UserCog size={24} />,
    'chart-line': <ChartLine size={24} />
  };
  return iconMap[iconName] || <Target size={24} />;
};