name: Trigger Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Vercel Deploy Hook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_pqWmNhDOkfHOyTTVNXQZcG2OemNQ/bJawppx1ks
