// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plnoqiktsyqwcwzlueri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbm9xaWt0c3lxd2N3emx1ZXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTIzNzQsImV4cCI6MjA2NTQ2ODM3NH0.s4K-4IorBrQmjcHOqYj1qjaHyjoYMPRQKksdobQ-Cw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);